// Created on 2024/3/12.
// Auth: wuxiaobo

export class AppPage{
  static readonly pageMain:string = 'pages/main/MainPage'
  static readonly pageAdvertising: string = 'pages/boot/AdvertisingPage';
  static readonly pageTextDemo: string = 'pages/home/ui/TextDemo';
  static readonly pageButtonDemo: string = 'pages/home/ui/ButtonDemo';
  static readonly pageImageDemo: string = 'pages/home/ui/ImageDemo';
  static readonly pageTextInputDemo: string = 'pages/home/ui/TextInputDemo';
  static readonly pageProgressDemo: string = 'pages/home/ui/ProgressDemo';
  static readonly pagePickerDemo: string = "pages/home/ui/PickerDemo";
  static readonly pageQrCodeDemo: string = "pages/home/ui/QRCodeDemo";
  static readonly pageToggleDemo: string = "pages/home/ui/ToggleDemo";
  static readonly pageSlideDemo: string = "pages/home/ui/SlideDemo";
  static readonly pageRatingDemo: string = "pages/home/ui/RatingDemo";
  static readonly pageSideBarDemo: string = "pages/home/ui/SideBarDemo";
  static readonly pageBadgeDemo: string = "pages/home/ui/BadgeDemo";
  static readonly pageRelativeDemo: string = "pages/home/ui/RelativeDemo";
  static readonly pageScrollDemo: string = "pages/home/ui/ScrollDemo";
  static readonly pageListDemo: string = "pages/home/ui/ListDemo";
  static readonly pageGridDemo: string = "pages/home/ui/GridDemo";
  static readonly pageSwiperDemo: string = "pages/home/ui/SwiperDemo";
  static readonly pageWebViewDemo: string = "pages/home/ui/WebViewDemo";
  static readonly pageVideoDemo: string = "pages/home/ui/VideoDemo";
  static readonly pageRefreshDemo: string = "pages/home/ui/RefreshDemo";
  static readonly pageLockDemo: string = "pages/home/ui/PatternLockDemo";
  static readonly pageNavigationDemo: string = "pages/home/ui/NavigationDemo";
  static readonly pageAlphabetIndexerDemo: string = "pages/home/ui/AlphabetIndexerDemo";
  static readonly pageNotificationDemo: string = "pages/lovecar/ui/NotificationDemo";
  static readonly pageStorageDemo: string = "pages/lovecar/ui/StorageDemo";
  static readonly pageEventDemo: string = "pages/lovecar/ui/EventDemo";
  static readonly pageLazyEachDemo: string = "pages/lovecar/ui/LazyForEachDemo";
}